"use strict";
/**
 *  Constants for anything Event related
 **/
 const actions = {
   EVENTS_MANAGING_RETRIEVED : "EVENTS_MANAGING_RETRIEVED",
   PUBLIC_EVENTS_RETRIEVED : "PUBLIC_EVENTS_RETRIEVED",
   PRIVATE_EVENTS_RETRIEVED : "PRIVATE_EVENTS_RETRIEVED",
   CURRENT_EVENT_SET : "CURRENT_EVENT_SET",
   EVENT_CREATED: "EVENT_CREATED",
   EVENT_UPDATED: "EVENT_UPDATED",
   FLAG_UPDATE_SET: "FLAG_UPDATED"
 };
 export default actions;
