"use strict";
/**
 *  Constants for anything Event related
 **/
 const actions = {
   UPCOMING_EVENTS_MANAGING_RETRIEVED : "UPCOMING_EVENTS_MANAGING_RETRIEVED",
   PAST_EVENTS_MANAGING_RETRIEVED : "PAST_EVENTS_MANAGING_RETRIEVED",
   PUBLIC_EVENTS_RETRIEVED : "PUBLIC_EVENTS_RETRIEVED",
   PRIVATE_EVENTS_RETRIEVED : "PRIVATE_EVENTS_RETRIEVED",
   CURRENT_EVENT_SET : "CURRENT_EVENT_SET",
   EVENT_CREATED: "EVENT_CREATED",
   EVENT_UPDATED: "EVENT_UPDATED",
   FLAG_UPDATE_SET: "FLAG_UPDATED",
   FLAG_DELETE_SET: "FLAG_UPDATED",
   EVENT_SEARCH: "EVENT_SEARCH",
   EVENT_DELETED: "EVENT_DELETED",
   CAL_EVENTS_FETCHED : 'CAL_EVENTS_FETCHED',
   EVENT_CHECKINS_RETRIEVED : 'EVENT_CHECKINS_RETRIEVED',
   EVENT_FILES_RETRIEVED : "EVENT_FILES_RETRIEVED",
   EVENT_CHECKIN_COUNTS_RETRIEVED : 'EVENT_CHECKIN_COUNTS_RETRIEVED',
   IMAGE_THUMB_STORED : "IMAGE_THUMB_STORED",
   IMAGE_URL_STORED : "IMAGE_URL_STORED",
   EVENT_FEED_RETRIEVED : 'EVENT_FEED_RETRIEVED',
   EVENT_MESSAGE_RECEIVED : 'EVENT_MESSAGE_RECEIVED',
   EVENT_MANAGERS_RETRIEVED : 'EVENT_MANAGERS_RETRIEVED',
   BULK_CHECKINS_RETRIEVED : 'BULK_CHECKINS_RETRIEVED',
   MANAGER_REMOVED : 'MANAGER_REMOVED',
   MANAGER_ADDED : 'MANAGER_ADDED',
   USER_RETRIEVED : 'USER_RETRIEVED',
   MESSAGE_SENT : 'MESSAGE_SENT',
   SUBMIT_FORM : 'SUBMIT_FORM',
   EVENT_INVITES_RETRIEVED : 'EVENT_INVITES_RETRIEVED',
   ATTENDEE_ADDED : 'ATTENDEE_ADDED',
   ATTENDEE_REMOVED : 'ATTENDEE_REMOVED',
   FILE_ADDED : 'FILE_ADDED',
   FILE_REMOVED : 'FILE_REMOVED',
   ERROR : 'ERROR'
 };
 export default actions;
